services:
  db_pg_container:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost || (PGPASSWORD='${POSTGRES_PASSWORD}' psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' >/dev/null)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s
    networks:
      - app-net

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - app-net

  app_container:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_URL: "${REDIS_URL}"
      JWT_ACCESS_TOKEN_SECRET: "${JWT_ACCESS_TOKEN_SECRET}"
      JWT_REFRESH_TOKEN_SECRET: "${JWT_REFRESH_TOKEN_SECRET}"
      JWT_ACCESS_TOKEN_EXPIRES: "${JWT_ACCESS_TOKEN_EXPIRES}"
      JWT_REFRESH_TOKEN_EXPIRES: "${JWT_REFRESH_TOKEN_EXPIRES}"
      DB_HOST: db_pg_container
      DB_PORT: "${PG_PORT}"
      APP_PORT: "${APP_PORT}"
      NODE_ENV: "${NODE_ENV}"
      COOKIE_DOMAIN: "${COOKIE_DOMAIN}"
      COOKIE_SECURE: "${COOKIE_SECURE}"
    depends_on:
      - db_pg_container
      - redis
    expose:
      - "${APP_PORT}"
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      NGINX_HTTP_PORT: "${NGINX_HTTP_PORT}"
      NGINX_HTTPS_PORT: "${NGINX_HTTPS_PORT}"
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      #- "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      #- ./deploy/nginx/certs:/etc/nginx/certs:ro # put certs here in prod
      - ./deploy/nginx/html:/usr/share/nginx/html:ro
      - ./deploy/nginx/logs:/var/log/nginx
    depends_on:
      - app_container
    networks:
      - app-net

volumes:
  pgdata:
  redisdata:

networks:
  app-net:
