services:
  db_pg_container:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: pmundo-db-prod
    env_file:
      - ../../.env.prod
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost || (PGPASSWORD='${POSTGRES_PASSWORD}' psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' >/dev/null)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s
    networks:
      - app-net

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    container_name: pmundo-redis-prod
    volumes:
      - redisdata:/data
    networks:
      - app-net

  app_container:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.prod
    container_name: pmundo-app-prod
    env_file:
      - ../../.env.prod
    environment:
      APP_PORT: "${APP_PORT}"
      SKIP_DB_WAIT: "${SKIP_DB_WAIT}"
      RUN_MIGRATIONS: "${RUN_MIGRATIONS}"
    depends_on:
      - db_pg_container
      - redis
    expose:
      - "${APP_PORT}"
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: pmundo-nginx-prod
    env_file:
      - ../../.env.prod
    environment:
      NGINX_HTTP_PORT: "${NGINX_HTTP_PORT}"
      NGINX_HTTPS_PORT: "${NGINX_HTTPS_PORT}"
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      #- "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      #- ../nginx/certs:/etc/nginx/certs:ro # put certs here in prod
      - ../nginx/html:/usr/share/nginx/html:ro
      - ../nginx/logs:/var/log/nginx
    depends_on:
      - app_container
    networks:
      - app-net

volumes:
  pgdata:
  redisdata:

networks:
  app-net:
